# =============================================================================
# Common Role - Handlers
# =============================================================================

---
- name: Restart SSH
  service:
    name: sshd
    state: restarted