# =============================================================================
# Microservices Role - Default Variables
# =============================================================================

---
docker_compose_dir: /home/vagrant/microservices
docker_network_name: microservices-net