# =============================================================================
# Ansible Inventory - Generated by Terraform
# =============================================================================

---
all:
  vars:
    ansible_user: ${ssh_user}
    ansible_ssh_private_key_file: ${ssh_private_key}
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    
    # Network Configuration
    network_prefix: "192.168.56"
    control_node_ip: "192.168.56.10"
    haproxy_ip: "${haproxy_ip}"
    microservices_ip: "${microservices_ip}"
    
    # HAProxy Configuration
    haproxy_frontend_port: 80
    haproxy_stats_port: ${haproxy_stats_port}
    haproxy_stats_user: "${haproxy_stats_user}"
    haproxy_stats_password: "${haproxy_stats_password}"
    
    # Microservices Configuration
    microservices_host: "${microservices_ip}"
    microservices:
%{ for name, svc in microservices ~}
      ${name}:
        name: "${svc.name}"
        port: ${svc.port}
        image: "${svc.image}"
%{ endfor ~}

  children:
    haproxy:
      hosts:
        vm-haproxy:
          ansible_host: ${haproxy_ip}
          
    microservices:
      hosts:
        vm-microservices:
          ansible_host: ${microservices_ip}