# =============================================================================
# HAProxy Role - Default Variables
# =============================================================================

---
haproxy_package: haproxy
haproxy_service: haproxy
haproxy_config_file: /etc/haproxy/haproxy.cfg

# Frontend
haproxy_frontend_name: "http_front"
haproxy_frontend_port: 80
haproxy_frontend_mode: "http"

# Stats
haproxy_stats_enabled: true
haproxy_stats_port: 8080
haproxy_stats_uri: "/stats"
haproxy_stats_user: "admin"
haproxy_stats_password: "haproxy_admin_2026"
haproxy_stats_refresh: "10s"
haproxy_stats_realm: "HAProxy Statistics"