# =============================================================================
# HAProxy Role - Handlers
# =============================================================================

---
- name: Restart HAProxy
  service:
    name: "{{ haproxy_service }}"
    state: restarted

- name: Reload HAProxy
  service:
    name: "{{ haproxy_service }}"
    state: reloaded