# -*- mode: ruby -*-
# vi: set ft=ruby :

# =============================================================================
# Vagrantfile for Control Node - KVM/Libvirt on openSUSE Tumbleweed
# =============================================================================

# Configuration Constants
BOX_NAME            = "generic/ubuntu2204"
VM_NAME             = "control-node"
VM_HOSTNAME         = "control-node"
VM_MEMORY           = 2048
VM_CPUS             = 2
VM_VCPU0_CPUSET     = "2"
VM_VCPU1_CPUSET     = "3"

# Network Configuration
CONTROL_NODE_IP     = "192.168.56.10"
NETWORK_NAME        = "infrastructure-net"
NETWORK_CIDR        = "192.168.56.0/24"
MANAGEMENT_NETWORK  = "192.168.121.0/24"

# Paths
SCRIPTS_PATH        = "../scripts"
PROJECT_ROOT        = "../.."

Vagrant.configure("2") do |config|
  config.vm.define VM_NAME do |node|
    node.vm.box      = BOX_NAME
    node.vm.hostname = VM_HOSTNAME

    node.vm.network "private_network",
      ip: CONTROL_NODE_IP,
      libvirt__network_name: NETWORK_NAME,
      libvirt__dhcp_enabled: false,
      libvirt__forward_mode: "nat"

    node.vm.synced_folder "#{PROJECT_ROOT}/terraform", "/home/vagrant/terraform",
      type: "nfs",
      nfs_version: 4,
      nfs_udp: false

    node.vm.synced_folder "#{PROJECT_ROOT}/ansible", "/home/vagrant/ansible",
      type: "nfs",
      nfs_version: 4,
      nfs_udp: false

    node.vm.synced_folder "#{PROJECT_ROOT}/ssh-keys", "/home/vagrant/ssh-keys",
      type: "nfs",
      nfs_version: 4,
      nfs_udp: false

    node.vm.provider "libvirt" do |libvirt|
      libvirt.driver            = "kvm"
      libvirt.memory            = VM_MEMORY
      libvirt.cpus              = VM_CPUS
      libvirt.cpu_affinity do |cpu|
        cpu.vcpu 0, cpuset: VM_VCPU0_CPUSET
        cpu.vcpu 1, cpuset: VM_VCPU1_CPUSET
      end
      libvirt.nested            = true
      libvirt.cpu_mode          = "host-passthrough"
      libvirt.storage_pool_name = "default"
      libvirt.machine_type      = "q35"
      
      # Graphics configuration (headless)
      libvirt.graphics_type = "none"
      libvirt.video_type    = "none"
      
      # Management network
      libvirt.management_network_name    = "vagrant-libvirt"
      libvirt.management_network_address = MANAGEMENT_NETWORK
      
      # QEMU guest agent channel
      libvirt.channel :type => 'unix',
        :target_name => 'org.qemu.guest_agent.0',
        :target_type => 'virtio'
    end

    # Provisioning scripts (executed in order)
    node.vm.provision "generate-ssh-keys",
      type: "shell",
      path: "#{SCRIPTS_PATH}/generate-ssh-keys.sh",
      privileged: false

    node.vm.provision "install-packages",
      type: "shell",
      path: "#{SCRIPTS_PATH}/install-packages.sh",
      privileged: true

    node.vm.provision "install-terraform",
      type: "shell",
      path: "#{SCRIPTS_PATH}/install-terraform.sh",
      privileged: true

    node.vm.provision "install-ansible",
      type: "shell",
      path: "#{SCRIPTS_PATH}/install-ansible.sh",
      privileged: true

    node.vm.provision "setup-terraform-providers",
      type: "shell",
      path: "#{SCRIPTS_PATH}/setup-terraform-providers.sh",
      privileged: false,
      env: {
        "INFRA_PROVIDER" => "libvirt"
      }

    node.vm.provision "configure-ansible",
      type: "shell",
      path: "#{SCRIPTS_PATH}/configure-ansible.sh",
      privileged: true

    node.vm.provision "create-helper-scripts",
      type: "shell",
      path: "#{SCRIPTS_PATH}/create-helper-scripts.sh",
      privileged: false,
      env: {
        "INFRA_PROVIDER" => "libvirt",
        "CONTROL_NODE_IP" => CONTROL_NODE_IP
      }

    # Final message
    node.vm.post_up_message = <<-MESSAGE
    ============================================
    Control Node (KVM/Libvirt) Ready!
    ============================================
    
    IP Address: #{CONTROL_NODE_IP}
    Provider:   KVM/Libvirt
    
    To deploy infrastructure:
      vagrant ssh
      cd ~
      ./deploy-infrastructure.sh
    
    ============================================
    MESSAGE
  end
end